### ISSUE TITLE
問題文を表示してカウントがスタートする場所について

### ISSUE THREAD

**Issue by KokitaS** [tosiki1202/thequiz#26]
現在の問題文生成後のフロー
問題文生成→格納→問題文表示→カウントスタート
実際のフロー
問題文生成→格納→シーン遷移→問題文表示→カウントスタート
現在一つのシーン内で作成しているため実際の形と異なっています。
MessageGeter.csの51行目messageManager.Q_Displaycontrol();
で問題文等格納後問題をすぐに表示しています。
各シーンの骨組み作成後書き換えることが必要です。

**Comment by tosiki1202** [comment]
😋
