### ISSUE TITLE
問題を生成するシーンを作ってください

### ISSUE THREAD

**Issue by KokitaS** [tosiki1202/thequiz#31]
現在のquizsceneの問題生成部分を問題を生成するためのシーンとして独立させることができればお願いできますか？
その時、quizsceneから問題文とボタン以外のオブジェクト消していただけるとありがたいです。

**Comment by tosiki1202** [comment]
ok

**Comment by tosiki1202** [comment]
作ってみたけど、どうでしょうか

**Comment by KokitaS** [comment]
ありがとうございます。
