### ISSUE TITLE
UIの改善予定

### ISSUE THREAD

**Issue by tosiki1202** [tosiki1202/thequiz#35]
以下の機能を実装予定

- 問題文・選択肢の表示を１文字ずつゆっくりにする
- 問題の生成中に、その旨を示すUIを表示し、生成後に自動でシーン遷移&1問目スタート

MessageManager.cs編集してる人いたらぶつかるかも

**Comment by KokitaS** [comment]
ok

**Comment by KokitaS** [comment]
”シーン遷移後と１問目”とか”問題と問題”の間が何もないので
第一問　みたいなの追加してもいいかもです

**Comment by tosiki1202** [comment]
これもじゃ
#39
