### ISSUE TITLE
リザルトシーンについて

### ISSUE THREAD

**Issue by KokitaS** [tosiki1202/thequiz#44]
問題終了後の画面に表示するものって何ですか？
以下必要そうなもの書いてます。必要か必要でないか、増やしたほうがいいものなど何かあればコメントお願いします
・画面遷移のためのボタン
・問題と解答をパネルで表示するためのボタン
・問題の正答数やタイムなどの情報←いる？(問題ごとに個別に表示する　か　正答数と合計時間のみ表示する)
・一人用の場合勝ち負けないけどどうするか

**Comment by tosiki1202** [comment]
1人用の場合なら、

- 問題のインデックス
- ⭕️か❌か
- その問題の詳細と自分の選択を表示するボタン
 
と画面遷移があれば十分でしょうか
もしくは、ジャンルが何かを表示できれば親切かもしれません

**Comment by KokitaS** [comment]
#47 にてとりあえずジャンルを除いてリザルトシーン更新してみました

**Comment by KokitaS** [comment]
#48 にてリザルトシーンの更新してみました
