### ISSUE TITLE
#55まで戻せますか？

### ISSUE THREAD

**Issue by KokitaS** [tosiki1202/thequiz#67]
私のブランチ"aaa"に#55以降追加したものを作成しmainとマージしてみましたがコンフリクト起きました。
またaaaのコードのみ採用した場合でも解消されなかったので#55まで戻せますか？
私の"teset3"ブランチにて#55をマージした時点にリセットした状態にし、その後"aaa"をpullしたところ問題なく動作しています。

**Comment by tosiki1202** [comment]
ok

**Comment by tosiki1202** [comment]
戻ってそうですか？

**Comment by tosiki1202** [comment]
もしあれでしたら、revertの内容を上からコミットしたmainブランチではなく、HEADを#55 時に合わせたrevert-branchがありますのでそちらにプルリクを送ってみてください

**Comment by KokitaS** [comment]
了解です
revertとresetで#55まで戻す方法が違うのでrevert-branchならコンフリクト起きないですね
mainの場合#55に完全に戻ってるわけじゃないのでコンフリクト起きるみたいです。

**Comment by tosiki1202** [comment]
手が滑って #69 マージしました

**Comment by KokitaS** [comment]
revert-branchの状態でいいならそれで行きたいんですけど
mainのrevertした状態からなら新しくもう一回つくらないとシーンのコンフリクト解消は時間かかりそうですね

**Comment by tosiki1202** [comment]
#70  令和最新版のブランチ：fix-branchをプッシュしました
revert-branchの内容をコピってmainの上からペースト・コミットしただけですが、うまく動くかもしれません
mainでresetしてpullしてみて！！！！！！！！！！！！！！！

**Comment by KokitaS** [comment]
pullしてみたらうまく動きました！！！！
プルリク承認しておきます
